version: '3'
services:
  sentinel:
    build: .
    network_mode: host  # To sniff the host network
    privileged: true  # For Scapy
  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/prometheus_rules.yml:/etc/prometheus/prometheus_rules.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
  web:
    build: .
    command: python src/app.py
    ports:
      - "5000:5000"
    depends_on:
      - prometheus
    environment:
      - FLASK_SECRET=supersecretkey
      - PROMETHEUS_URL=http://localhost:9090